apiVersion: 1.0.0
metadata:
  name: localnews-frontend
projects:
  - name: localnews
    source:
      type: git
      location: 'https://github.com/Apress/Kubernetes-Native-Development'
components:
  -  alias: nodejs
     type: dockerimage
     image: 'registry.redhat.io/devspaces/udi-rhel8@sha256:1983e5…'
    memoryLimit: 2048Mi
    endpoints:
      - name: news-frontend
        port: 4200
        attributes:
          discoverable: 'true'
          public: 'true'
    mountSources: true
