# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: tdolby/experimental:ace-basic-mqclient-12.0.4.0
      env:
        LICENSE: accept

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Build/UT for ACE projects
        run: |
          ########################################################################
          # 
          # Set up ACE environment
          # 
          ########################################################################
          echo $MQSI_REGISTRY
          . /opt/ibm/ace-12/server/bin/mqsiprofile

          ########################################################################
          # 
          # Run the build and unit test phases
          # 
          ########################################################################
          cd build
          echo "Creating work directory"
          mqsicreateworkdir /tmp/ace-demo-sap-work-dir
          echo "Running build/package"
          ibmint deploy --input-path . --output-work-directory /tmp/ace-demo-sap-work-dir --project SAPApplication --project SAPApplication_UnitTest
          echo "Optimizing startup"
          ibmint optimize server --work-dir /tmp/ace-demo-sap-work-dir --disable NodeJS
          echo "Running tests"
          IntegrationServer -w /tmp/ace-demo-sap-work-dir --mq-queue-manager-name dummy --start-msgflows false --no-nodejs --admin-rest-api -1 --test-project SAPApplication_UnitTest
